import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
// import dbConnecte from "@/lib/dbConnect";

export const metadata: Metadata = {
  title: "Mystry Messages",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
